<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Listening.Domain\Listening.Domain.csproj" />
    <ProjectReference Include="..\Zheng.Infrastructure\Zheng.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4"/>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>
</Project>