<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Opportunity.LrcParser" Version="1.0.4" />
    <PackageReference Include="SubtitlesParser" Version="1.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zheng.Commons\Zheng.Commons.csproj" />
    <ProjectReference Include="..\Zheng.DomainCommons\Zheng.DomainCommons.csproj" />
  </ItemGroup>

</Project>
