<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zheng.Commons\Zheng.Commons.csproj" />
    <ProjectReference Include="..\Zheng.JWT\Zheng.JWT.csproj" />
  </ItemGroup>

</Project>
